language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - nosetests
  - nosetests --with-coverage
after_success:
  - coveralls